/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ctommasi <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/01/07 14:44:29 by ctommasi          #+#    #+#             */
/*   Updated: 2025/01/07 14:44:32 by ctommasi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./includes/ft_printf.h"
#include "./includes/ft_printf_bonus.h"
#include <limits.h>

int	main(void)
{
	void	*x;
	void	*ptr;
	char	*null_str;
	char	*str;
	int		n;

	ptr = &x;
	null_str = NULL;
	str = "HELLO WORLD";
	n = 0;
	// printf("----------------------------------------- (char)\n");
	// n = ft_printf("FT =\t[%c]\t\t- ", 'X');
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%c]\t\t- ", 'X');
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (str)\n");
	// n = ft_printf("FT =\t[%s]\t- ", str);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%s]\t- ", str);
	// printf("(%d)\n\n", n);
	printf("----------------------------------------- (null)\n");
	n = ft_printf("FT =\t[%s]\t- ", null_str);
	printf("(%d)\n", n);
	n = printf("OG =\t[%s]\t- ", null_str);
	printf("(%d)\n\n", n);
	// printf("----------------------------------------- (04d)\n");
	// n = ft_printf("FT =\t[%04d]\t\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%04d]\t\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (010d)\n");
	// n = ft_printf("FT =\t[%010d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%010d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+d with 0)\n");
	// n = ft_printf("FT =\t[%+d]\t\t- ", 0);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+d]\t\t- ", 0);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (d with INT_MAX)\n");
	// n = ft_printf("FT =\t[%d]\t- ", INT_MAX);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%d]\t- ", INT_MAX);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (.5d)\n");
	// n = ft_printf("FT =\t[%.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (.5d with 0)\n");
	// n = ft_printf("FT =\t[%.5d]\t\t- ", 0);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%.5d]\t\t- ", 0);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (10.5d)\n");
	// n = ft_printf("FT =\t[%10.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%10.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+0.5d)\n");
	// n = ft_printf("FT =\t[%+0.5d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+0.5d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+10d)\n");
	// n = ft_printf("FT =\t[%d]\t\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%d]\t\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+0d)\n");
	// n = ft_printf("FT =\t[%+0d]\t\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+0d]\t\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-10.5d)\n");
	// n = ft_printf("FT =\t[%-10.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-10.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+010d)\n");
	// n = ft_printf("FT =\t[%+010d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+010d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-+10.5d)\n");
	// n = ft_printf("FT =\t[%-+10.5d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-+10.5d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- ( 10d)\n");
	// n = ft_printf("FT =\t[% 10d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[% 10d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- ( 10.5d)\n");
	// n = ft_printf("FT =\t[% 10.5d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[% 10.5d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+10.5d)\n");
	// n = ft_printf("FT =\t[%+10.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+10.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (- 10.5d)\n");
	// n = ft_printf("FT =\t[%- 10.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%- 10.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (+-10.5d)\n");
	// n = ft_printf("FT =\t[%+-10.5d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%+-10.5d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-010.5d)\n");
	// n = ft_printf("FT =\t[%-010.5d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-010.5d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-05d)\n");
	// n = ft_printf("FT =\t[%-05d]\t\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-05d]\t\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (010.5d)\n");
	// n = ft_printf("FT =\t[%010.5d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%010.5d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-10d)\n");
	// n = ft_printf("FT =\t[%-10d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-10d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- ( 010d)\n");
	// n = ft_printf("FT =\t[% 010d]\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[% 010d]\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (d with INT_MIN)\n");
	// n = ft_printf("FT =\t[%d]\t- ", INT_MIN);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%d]\t- ", INT_MIN);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (pos x)\n");
	// n = ft_printf("FT =\t[%X]\t\t- ", 100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%X]\t\t- ", 100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (pos #x)\n");
	// n = ft_printf("FT =\t[%#x]\t\t- ", 100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#x]\t\t- ", 100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (INT_MAX x)\n");
	// n = ft_printf("FT =\t[%x]\t- ", INT_MAX);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%x]\t- ", INT_MAX);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (neg x)\n");
	// n = ft_printf("FT =\t[%x]\t- ", -10);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%x]\t- ", -10);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (INT_MIN x)\n");
	// n = ft_printf("FT =\t[%x]\t- ", INT_MIN);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%x]\t- ", INT_MIN);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (neg #x)\n");
	// n = ft_printf("FT =\t[%#x]\t- ", -100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#x]\t- ", -100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (pos X)\n");
	// n = ft_printf("FT =\t[%X]\t\t- ", 100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%X]\t\t- ", 100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (pos #X)\n");
	// n = ft_printf("FT =\t[%#X]\t\t- ", 100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#X]\t\t- ", 100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (neg X)\n");
	// n = ft_printf("FT =\t[%X]\t- ", -100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%X]\t- ", -100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (neg #X)\n");
	// n = ft_printf("FT =\t[%#X]\t- ", -100);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#X]\t- ", -100);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (ptr)\n");
	// n = ft_printf("FT =   [%#p] - ", ptr);
	// printf("(%d)\n", n);
	// n = printf("OG =   [%#p] - ", ptr);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (nil ptr)\n");
	// n = ft_printf("FT =\t[%p]\t\t- ", null_str);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%p]\t\t- ", null_str);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (unsigned)\n");
	// n = ft_printf("FT =\t[%#u]\t\t- ", 420);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#u]\t\t- ", 420);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (unsigned neg)\n");
	// n = ft_printf("FT =\t[%u]\t- ", -420);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%u]\t- ", -420);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (.0d)\n");
	// n = ft_printf("FT =\t[%.0d]\t\t- ", 0);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%.0d]\t\t- ", 0);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (d with 0)\n");
	// n = ft_printf("FT =\t[%d]\t\t- ", 0);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%d]\t\t- ", 0);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (empty str)\n");
	// n = ft_printf("FT =\t[%s]\t\t- ", "");
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%s]\t\t- ", "");
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (negative zero d)\n");
	// n = ft_printf("FT =\t[%0-10d]\t- ", -42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%0-10d]\t- ", -42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (zero precision u)\n");
	// n = ft_printf("FT =\t[%.0u]\t\t- ", 0);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%.0u]\t\t- ", 0);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (unsigned MAX)\n");
	// n = ft_printf("FT =\t[%u]\t- ", UINT_MAX);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%u]\t- ", UINT_MAX);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (pointer nil)\n");
	// n = ft_printf("FT =\t[%p]\t\t- ", NULL);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%p]\t\t- ", NULL);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- ( d)\n");
	// n = ft_printf("FT =\t[% d]\t\t- ", 42);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[% d]\t\t- ", 42);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (%% with padding)\n");
	// n = ft_printf("FT =\t[%5%]\t\t- ");
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%5%]\t\t- ");
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-010.5d)\n");
	// n = ft_printf("FT =\t[%-010.5d]\t- ", 123);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-010.5d]\t- ", 123);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (0-10.5d)\n");
	// n = ft_printf("FT =\t[%0-10.5d]\t- ", -12345);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%0-10.5d]\t- ", -12345);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-#10x)\n");
	// n = ft_printf("FT =\t[%-#10x]\t- ", 0x1AB);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-#10x]\t- ", 0x1AB);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (5c)\n");
	// n = ft_printf("FT =\t[%5c]\t\t- ", 'X');
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%5c]\t\t- ", 'X');
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-5c)\n");
	// n = ft_printf("FT =\t[%-5c]\t\t- ", 'X');
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-5c]\t\t- ", 'X');
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (05c)\n");
	// n = ft_printf("FT =\t[%05c]\t\t- ", 'X');
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%05c]\t\t- ", 'X');
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (010X)\n");
	// n = ft_printf("FT =\t[%010X]\t- ", 0xABC);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%010X]\t- ", 0xABC);
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (-10s)\n");
	// n = ft_printf("FT =\t[%-10s]\t- ", "TEST");
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%-10s]\t- ", "TEST");
	// printf("(%d)\n\n", n);
	// printf("----------------------------------------- (#.4x)\n");
	// n = ft_printf("FT =\t[%#.4x]\t- ", 0x123);
	// printf("(%d)\n", n);
	// n = printf("OG =\t[%#.4x]\t- ", 0x123);
	// printf("(%d)\n\n", n);
	printf("----------------------------------------- (s & d)\n");
	n = ft_printf("FT =\t[%s] and fav num = %d ", str, 42);
	printf("(%d)\n", n);
	n = printf("OG =\t[%s] and fav num = %d ", str, 42);
	printf("(%d)\n\n", n);
	return (0);
}
